### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Sumit123rox** [ResoCoder/databinding-with-livedata-tutorial#3]
When i'm trying your code i got below error message when i run it.

e: error: Bindable must be on a member in an Observable class. MainViewModel is not Observable.

![error](https://user-images.githubusercontent.com/24592153/64062189-423f7780-cc01-11e9-88d3-fecabd585f3c.png)

**Comment by Sumit123rox** [comment]
If you'r using latest version of android studio (mine is 3.6 canary 9),  you've to implement Observable interface and implement its methods like below:

private val callbacks: PropertyChangeRegistry by lazy { PropertyChangeRegistry() }

    override fun removeOnPropertyChangedCallback(callback: Observable.OnPropertyChangedCallback?) {
        callbacks.add(callback)
    }

    override fun addOnPropertyChangedCallback(callback: Observable.OnPropertyChangedCallback?) {
        callbacks.remove(callback)
    }

And you'r good to go!!!!!
Now you can use @Bindable in your ViewModel Class.

**Comment by riyaspullurofficial** [comment]
thanks Sumit
